# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ZeroPhone Newsletter
email: crimier@yandex.ru
description: > # this means to ignore newlines until "baseurl:"
  ZeroPhone weekly worklog newsletter: Pi-powered open-source mobile phone (that you can assemble for 50$ in parts)
  
  
  
baseurl: "/newsletter" # the subpath of your site, e.g. /blog
url: "https://zerophone.github.io" # the base hostname & protocol for your site

#sidebar
default-image: ZeroPhone1.jpg # If there is no featured image in a post then this image will be showed. Also on all pages this image will be showed. Use a 500x250 image.

#footer
built-by: webjeda
copyright:
   name: ZeroPhone
   link: 'https://hackaday.io/project/19035'

# Build settings
markdown: kramdown
permalink: /:title/
paginate: 6
paginate_path: /page:num/

# Tracker
#analytics: UA-83979019-1

# Comments
#disqus-shortname: webjeda-demo

#social
#facebook: http://facebook.com/webjeda
#quora: http://quora.com/sharathdt
twitter: http://twitter.com/@ZeroPhoneOSHW
github: http://github.com/ZeroPhone/

#facebook like box
#fb-app-id: 549480635219583
#fb-page-url: https://www.facebook.com/webjeda/
#fb-page-title: webjeda

# Sass style
sass:
  style: compressed

# Ruby Gems
gems: [jekyll-paginate, jekyll-seo-tag]
